# Generated by Django 4.2.1 on 2023-05-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0002_alter_competence_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='компетенции (действие)',
            new_name='Действия',
        ),
    ]
