# Generated by Django 4.2.1 on 2023-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0003_alter_competence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='international',
            name='Jobs',
            field=models.ManyToManyField(to='competences.jobs', verbose_name='Конкретика'),
        ),
        migrations.AddField(
            model_name='international',
            name='competences',
            field=models.ManyToManyField(to='competences.competence', verbose_name='Компетенции'),
        ),
        migrations.AddField(
            model_name='international',
            name='standards',
            field=models.ManyToManyField(to='competences.standards', verbose_name='Действия'),
        ),
    ]
